import * as React from 'react';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Container from '@mui/material/Container';
import CssBaseline from '@mui/material/CssBaseline';

import { Header } from '@/components';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Orinoco - Cameras shopping site',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <React.Fragment>
          <CssBaseline />
          <Container disableGutters maxWidth={false}>
        <Header />
        {children}
          </Container>
        </React.Fragment>
      </body>
    </html>
  );
}
